name: Create GitHub Release
on:
  push: 
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
            body_file: CHANGELOG.text
