name: Pull request

on: 
  pull_request:
    branches: [main, devel]

jobs: 
  draft_release:
    env:
      GITHUB_ACTIONS: false
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Checkout branch
        run: git checkout $GITHUB_HEAD_REF
      - name: Create draft
        run: GITHUB_ACTIONS=false node test.js

