name: Pull request

on: 
  pull_request:
    branches: [main, devel]

jobs: 
  draft_release:
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: devel
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Create draft with standard-version
        id: build_changelog
        run: |
         body=$(npx standard-version --dry-run --silent)
         body="${body//'%'/'%25'}"
         body="${body//$'\n'/'%0A'}"
         body="${body//$'\r'/'%0D'}"
         echo "::set-output name=body::"${body}""
      - name: Comment standard-version preview
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Hey 👋!
            This is a preview of your release notes, based on your commits.
            In case you want to change it, you can rebase and adjust your commit messages according to [conventional commits](https://www.conventionalcommits.org/).
            ${{ steps.build_changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

