name: Pull request

on: 
  pull_request:
    branches:
      - main

jobs: 
  draft_release:
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - run: echo $(git branch --show-current)
      - name: Create draft
        run: npx standard-version --dry-run
