name: Pull request

on: 
  pull_request:
    branches:
      - main

jobs: 
  draft_release:
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo $(git branch --show-current)
      - name: Install dependencies
        run: npm ci
      - name: Create draft with standard-version
        run: npx standard-version --dry-run
      - name: Create draft with semantic-release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

