name: Pull request

on: 
  pull_request:
    branches: [main, devel]

jobs: 
  draft_release:
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Echo current branch
        run: |
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          echo $(git branch --show-current)
      - name: Checkout branch
        run: git checkout $GITHUB_HEAD_REF
      - name: Build
        run: npm run build
      - name: Create draft
        id: build-release-notes
        uses: ./
      - name: Comment standard-version preview
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## 👋 Hey there!
            Thank you for you contribution. Below is a preview of the release notes if your PR gets merged.
            Please, make sure it includes all your significant changes with descriptive messages.
            Keep in mind that release notes are automatically generated from the commit messages according to [conventional commits](https://www.conventionalcommits.org/).
            If you feel like you need to change anything, please take a look into [this guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#addressing-review-feedback) to learn how you can fixup your commits.
            
            ---
            
            ${{ steps.build-release-notes.outputs.releaseNotes }}

