name: Pull request

on: 
  pull_request:
    branches: [main, devel]

jobs: 
  draft_release:
    runs-on: ubuntu-latest
    name: Draft release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Checkout branch
        run: git checkout $GITHUB_HEAD_REF
      - name: Echo current branch
        run: |
          echo $GITHUB_HEAD_REF
          echo $(git branch --show-current)
      - name: Test env ci
        run: node test.js
        env:
          GITHUB_ACTIONS: false
      - name: Create draft
        run: npx semantic-release --no-ci --dry-run

