name: Release

on:  
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Create version
        run: npx standard-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: npm publish
      - name: Generate release note
        run: npx standard-version --dry-run --output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate release note
        run: npx conventional-changelog -p angular > CHANGELOG.text
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
            body_file: CHANGELOG.text
