name: Release

on:  
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Setup git
        run: |
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git config --global user.name "{{ github.actor }}"
      - name: Create version
        run: npx standard-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Publish to npm
      #   run: npm publish
      - name: Generate release note
        run: npx conventional-changelog -p angular > CHANGELOG.text
